services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: onono
      POSTGRES_PASSWORD: onono
      POSTGRES_DB: onono
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
